<script setup lang="ts">
import { locations, getGoogleMapsLink, getGoogleMapsEmbedUrl } from '~/config/locations'
import { services } from '~/config/services'
import { usePageSeo } from '~/composables/usePageSeo'
const name = ref(''), service = ref(''), detail = ref('')
const message = computed(() => `Halo Bengkel Bubut Damai, saya ${name.value.trim()}.\nLayanan: ${service.value}\nKebutuhan: ${detail.value.trim()}`)
function submit() { window.open(`https://wa.me/6281517281614?text=${encodeURIComponent(message.value)}`, '_blank', 'noopener,noreferrer') }
usePageSeo('Kontak & Penawaran Gear | Bengkel Bubut Damai','Konsultasikan gear, komponen transmisi, custom gear, atau repair komponen melalui WhatsApp. Temukan bengkel kami di Kapuk dan Pangeran Jayakarta.','/contact')
</script><template><div><section class="page-intro"><div class="container"><p class="eyebrow">KONTAK / MULAI PERCAKAPAN</p><h1>Gear dan komponen,<br>siap kami <em>kerjakan.</em></h1><p>Diskusikan kebutuhan pengerjaan Anda,<br>atau kunjungi salah satu lokasi bengkel kami.</p></div></section><section id="penawaran" class="section"><div class="container contact-layout"><div><p class="eyebrow">MARI TERHUBUNG</p><h2>Mulai dari<br>konsultasi.</h2><p class="heading-description">Ceritakan kebutuhan Anda melalui formulir.<br>Pesan akan disiapkan di WhatsApp untuk Anda kirim.</p><a class="contact-phone" href="tel:+6281517281614">0815 1728 1614 ↗</a><div class="hours"><h3>Jam operasional</h3><p><span>Senin–Jumat</span><span>08.00–17.00 WIB</span></p><p><span>Sabtu</span><span>08.00–14.00 WIB</span></p><p><span>Minggu</span><span>Tutup</span></p></div></div><form class="quote-form" @submit.prevent="submit"><h3>Ceritakan kebutuhan Anda</h3><label for="name">Nama / perusahaan</label><input id="name" v-model="name" autocomplete="name" placeholder="Nama Anda atau perusahaan" required maxlength="120" pattern=".*\S.*" /><label for="service">Layanan yang dibutuhkan</label><select id="service" v-model="service" required><option value="" disabled>Pilih layanan</option><option v-for="item in services" :key="item.title">{{ item.title }}</option><option>Konsultasi terlebih dahulu</option></select><label for="detail">Detail kebutuhan</label><textarea id="detail" v-model="detail" rows="5" required minlength="10" maxlength="2000" placeholder="Jenis gear, komponen transmisi, material, ukuran, jumlah, dan target waktu pengerjaan..." /><p class="form-note">Foto atau gambar kerja dapat dilampirkan setelah WhatsApp terbuka.</p><button type="submit" class="button button-dark">Lanjutkan ke WhatsApp <span>↗</span></button></form></div></section><section class="section work-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">KUNJUNGI KAMI</p><h2>Dua lokasi.<br>Satu perhatian pada detail.</h2></div><p class="heading-description">Hubungi kami sebelum berkunjung<br>untuk koordinasi kebutuhan Anda.</p></div><div class="locations-grid"><article v-for="(location,i) in locations" :key="location.name" class="location-card"><div class="location-text"><p class="eyebrow">LOKASI / 0{{ i+1 }}</p><h3>{{ location.name }}</h3><p>{{ location.address }}</p></div><iframe :src="getGoogleMapsEmbedUrl(location)" :title="`Peta ${location.name}`" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen /><a :href="getGoogleMapsLink(location)" target="_blank" rel="noopener noreferrer" class="text-link">Petunjuk Arah <span>↗</span></a></article></div></div></section></div></template>
