<script setup lang="ts">
import { services } from '~/config/services'
import { portfolioItems } from '~/config/portfolio'
import { usePageSeo } from '~/composables/usePageSeo'
const featured = [portfolioItems[11],portfolioItems[10],portfolioItems[7]]
usePageSeo('Bengkel Bubut Gear & Komponen Transmisi Jakarta | Bengkel Bubut Damai','Bengkel Bubut Damai spesialis gear dan komponen transmisi, melayani custom gear, shaft, keyway, bushing, dan repair komponen di Jakarta.','/')
useHead({script:[{type:'application/ld+json',innerHTML:JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',name:'Bengkel Bubut Damai',url:'https://bubutdamai.com',telephone:'+6281517281614',areaServed:'Jakarta',image:'https://bubutdamai.com/images/hero.webp'})}]})
</script>
<template><div>
<section class="hero"><div class="hero-photo"><img src="/images/hero.webp" alt="Detail gear dan komponen logam hasil pekerjaan Bengkel Bubut Damai" fetchpriority="high" width="1200" height="1600" /></div><div class="container hero-inner"><div class="hero-copy"><p class="eyebrow"><span class="gold-line"></span> SPESIALIS GEAR & KOMPONEN MESIN · JAKARTA</p><h1>Ketelitian di<br>setiap <em>putaran.</em></h1><p class="hero-description">Bengkel Bubut Damai berfokus pada pengerjaan gear dan komponen transmisi—dari custom gear hingga repair sesuai contoh atau spesifikasi.</p><div class="actions"><WhatsAppButton text="Konsultasikan Kebutuhan" /><NuxtLink class="text-link light" to="/portfolio">Lihat Hasil Pekerjaan <span>↗</span></NuxtLink></div><div class="hero-notes"><span>01 / SPESIALIS GEAR</span><span>02 / KOMPONEN TRANSMISI</span></div></div><div class="photo-caption"><span>DETAIL YANG BERBICARA</span><p>Komponen nyata.<br>Hasil kerja kami sendiri.</p></div></div></section>
<div class="material-bar"><div class="container"><span>KEAHLIAN KAMI</span><span>Gear & Transmisi</span><i>+</i><span>Custom Gear</span><i>+</i><span>Shaft & Keyway</span><i>+</i><span>Repair Komponen</span></div></div>
<section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">01 / LAYANAN KAMI</p><h2>Solusi pengerjaan.<br>Untuk berbagai kebutuhan.</h2></div><NuxtLink to="/services" class="text-link">Jelajahi Layanan <span>↗</span></NuxtLink></div><div class="service-grid"><NuxtLink v-for="(service,i) in services" :key="service.title" :to="`/services#layanan-${i}`" class="service-tile"><div class="tile-top"><span>0{{ i+1 }}</span><span aria-hidden="true">↗</span></div><h3>{{ service.title }}</h3><p>{{ service.short }}</p><span class="tile-bottom">{{ service.material }}</span></NuxtLink></div></div></section>
<section class="section work-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">02 / HASIL PEKERJAAN</p><h2>Kualitas terlihat<br>dari detailnya.</h2></div><div><p class="heading-description">Lihat lebih dekat beberapa komponen<br>yang telah kami kerjakan.</p><NuxtLink to="/portfolio" class="text-link">Semua Hasil Pekerjaan <span>↗</span></NuxtLink></div></div><div class="project-grid"><NuxtLink v-for="(item,i) in featured" :key="item.image" to="/portfolio" class="project-card"><div class="project-image"><img :src="`/images/${item.image}`" :alt="item.title" loading="lazy" width="600" height="750" /><span class="image-arrow">↗</span></div><div class="project-meta"><span>0{{ i+1 }} / {{ item.category }}</span><h3>{{ item.title }}</h3></div></NuxtLink></div></div></section>
<section class="section"><div class="container process-layout"><div><p class="eyebrow">03 / CARA KAMI BEKERJA</p><h2>Kebutuhan Anda.<br>Perhatian kami.</h2><p class="heading-description">Komunikasi yang jelas sejak awal,<br>agar pengerjaan memiliki arah yang tepat.</p><NuxtLink to="/contact" class="text-link">Kenali Bengkel Kami <span>↗</span></NuxtLink></div><div class="steps"><article v-for="(step,i) in [{title:'Ceritakan kebutuhan Anda',text:'Kirim foto komponen, gambar kerja, ukuran, dan jumlah yang dibutuhkan.'},{title:'Diskusikan spesifikasi & penawaran',text:'Kami membahas material, lingkup pekerjaan, estimasi biaya, dan waktu pengerjaan.'},{title:'Pengerjaan & pemeriksaan',text:'Komponen dikerjakan dan diperiksa sesuai spesifikasi yang telah disepakati.'}]" :key="step.title"><span>0{{ i+1 }}</span><div><h3>{{ step.title }}</h3><p>{{ step.text }}</p></div></article></div></div></section><ProjectCta /></div></template>
