<script setup lang="ts">
import { portfolioItems, type PortfolioItem } from '~/config/portfolio'
import { usePageSeo } from '~/composables/usePageSeo'
const categories = ['Semua',...new Set(portfolioItems.map(item => item.category))]
const active = ref('Semua')
const filtered = computed(() => active.value === 'Semua' ? portfolioItems : portfolioItems.filter(item => item.category === active.value))
const selected = ref<PortfolioItem | null>(null)
const modal = ref<HTMLDialogElement | null>(null)
function show(item:PortfolioItem) { selected.value = item; modal.value?.showModal() }
function close() { modal.value?.close() }
usePageSeo('Hasil Pekerjaan Gear & Komponen Transmisi | Bengkel Bubut Damai','Galeri hasil pengerjaan gear, komponen transmisi, shaft, keyway, bushing, dan repair gear Bengkel Bubut Damai.','/portfolio')
</script><template><div><section class="page-intro"><div class="container"><p class="eyebrow">PORTOFOLIO / HASIL PEKERJAAN</p><h1>Bukti kerja.<br>Dalam setiap <em>detail.</em></h1><p>Dokumentasi komponen dan hasil pengerjaan kami.<br>Pilih kategori, lalu buka foto untuk melihat lebih dekat.</p></div></section><section class="section"><div class="container"><div class="filter-bar" aria-label="Filter kategori"><button v-for="category in categories" :key="category" :aria-pressed="active === category" :class="{active: active === category}" @click="active = category">{{ category }}</button></div><p class="result-count" aria-live="polite">{{ filtered.length }} hasil pekerjaan</p><div class="project-grid portfolio-grid"><button v-for="item in filtered" :key="item.image" class="project-card" @click="show(item)"><div class="project-image"><img :src="`/images/${item.image}`" :alt="item.title" width="600" height="750" loading="lazy" /><span class="image-arrow">↗</span></div><div class="project-meta"><span>{{ item.category }}</span><h2>{{ item.title }}</h2></div></button></div></div></section><dialog ref="modal" class="project-dialog" @click="(event) => { if(event.target === modal) close() }"><div v-if="selected" class="dialog-content"><button class="dialog-close" aria-label="Tutup detail foto" @click="close">×</button><img :src="`/images/${selected.image}`" :alt="selected.title" /><div class="dialog-description"><p class="eyebrow">{{ selected.category }}</p><h2>{{ selected.title }}</h2><p>{{ selected.description }}</p><WhatsAppButton text="Diskusikan Part Serupa" :message="`Halo Bengkel Bubut Damai, saya ingin konsultasi komponen seperti ${selected.title} di portofolio.`" /></div></div></dialog><ProjectCta /></div></template>
